# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e9fe343ad1eb27120b8a080128731806a32762ad656a18d208b949b94daa87aca9e41fb1d6ca6ea118d9f563fcd5cef9493aaf89720a13f77ec26888bfedbc9

test:
  secret_key_base: ca9a1c9a83c0a8494c5dd30158bc8891d451be7f8c2234873a78d607d933a7e90a0cb18105120068bce1541eb705f3537fca3b7f7261bc20dfd8c7338b056960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
